#include "spi.h"

void SPI_GPIO_Config(SPI_TypeDef *SPI){
    if(SPI==SPI2){
        WRITE_REG_FIELD(RCC->APB1ENR,RCC_APB1ENR_SPI2EN,1);
        WRITE_REG_FIELD(RCC->AHB1ENR, RCC_AHB1ENR_GPIOBEN, 1);
        // do two dummy reads after enabling the peripheral clock, as per the errata
        volatile unsigned int dummy;
        dummy = (RCC->AHB1ENR);
        dummy = (RCC->AHB1ENR);

        /*SPI2 Pins*/
        WRITE_REG_FIELD(GPIOB->MODER,GPIO_MODER_MODER9,1); //SPI2_NSS
        WRITE_REG_FIELD(GPIOB->OSPEEDR,GPIO_OSPEEDER_OSPEEDR9,3);
        WRITE_REG_FIELD(GPIOB->MODER,GPIO_MODER_MODER15,2); //SPI2_MOSI
        WRITE_REG_FIELD(GPIOB->AFR[1],GPIO_AFRH_AFRH7,5);
        WRITE_REG_FIELD(GPIOB->OSPEEDR,GPIO_OSPEEDER_OSPEEDR15,3);
        WRITE_REG_FIELD(GPIOB->MODER,GPIO_MODER_MODER14,2); //SPI2_MISO
        WRITE_REG_FIELD(GPIOB->AFR[1],GPIO_AFRH_AFRH6,5);
        WRITE_REG_FIELD(GPIOB->OSPEEDR,GPIO_OSPEEDER_OSPEEDR14,3);
        WRITE_REG_FIELD(GPIOB->MODER,GPIO_MODER_MODER13,2); //SPI2_SCk
        WRITE_REG_FIELD(GPIOB->AFR[1],GPIO_AFRH_AFRH5,5);
        WRITE_REG_FIELD(GPIOB->OSPEEDR,GPIO_OSPEEDER_OSPEEDR13,3);
    } 

    if(SPI==SPI3){
        WRITE_REG_FIELD(RCC->APB1ENR,RCC_APB1ENR_SPI3EN,1);
        WRITE_REG_FIELD(RCC->AHB1ENR, RCC_AHB1ENR_GPIOCEN, 1);
        WRITE_REG_FIELD(RCC->AHB1ENR, RCC_AHB1ENR_GPIOAEN, 1);
        // do two dummy reads after enabling the peripheral clock, as per the errata
        volatile unsigned int dummy;
        dummy = (RCC->AHB1ENR);
        dummy = (RCC->AHB1ENR);
        /*SPI3 Pins*/
        WRITE_REG_FIELD(GPIOA->MODER,GPIO_MODER_MODER4,2); //SPI3_NSS
        WRITE_REG_FIELD(GPIOA->AFR[0],GPIO_AFRL_AFRL4,6);
        WRITE_REG_FIELD(GPIOA->OSPEEDR,GPIO_OSPEEDER_OSPEEDR4,3);
        WRITE_REG_FIELD(GPIOC->MODER,GPIO_MODER_MODER12,2); //SPI3_MOSI
        WRITE_REG_FIELD(GPIOC->AFR[1],GPIO_AFRH_AFRH4,6);
        WRITE_REG_FIELD(GPIOC->OSPEEDR,GPIO_OSPEEDER_OSPEEDR12,3);
        WRITE_REG_FIELD(GPIOC->MODER,GPIO_MODER_MODER11,2); //SPI3_MISO
        WRITE_REG_FIELD(GPIOC->AFR[1],GPIO_AFRH_AFRH3,6);
        WRITE_REG_FIELD(GPIOC->OSPEEDR,GPIO_OSPEEDER_OSPEEDR11,3);
        WRITE_REG_FIELD(GPIOC->MODER,GPIO_MODER_MODER10,2); //SPI3_SCk
        WRITE_REG_FIELD(GPIOC->AFR[1],GPIO_AFRH_AFRH2,6);
        WRITE_REG_FIELD(GPIOC->OSPEEDR,GPIO_OSPEEDER_OSPEEDR10,3);
    }

}

void SPI_Master_Init(SPI_TypeDef *SPI){

    WRITE_REG_FIELD(SPI->CR1,SPI_CR1_BR,0x3); // APBxCLK/16
    WRITE_REG_FIELD(SPI->CR1,SPI_CR1_CPOL,1);
    WRITE_REG_FIELD(SPI->CR1,SPI_CR1_CPHA,1);

    WRITE_REG_FIELD(SPI->CR1,SPI_CR1_LSBFIRST,0);
    WRITE_REG_FIELD(SPI->CR1,SPI_CR1_SSM,1);
    WRITE_REG_FIELD(SPI->CR1,SPI_CR1_SSI,1);
    WRITE_REG_FIELD(SPI->CR1,SPI_CR1_RXONLY,0);
    WRITE_REG_FIELD(SPI->CR1,SPI_CR1_DFF,0);

    WRITE_REG_FIELD(SPI->CR1,SPI_CR1_MSTR,1);

    WRITE_REG_FIELD(SPI->CR2,SPI_CR2_FRF,0);
    //WRITE_REG_FIELD(SPI->CR2,SPI_CR2_SSOE,1);
}



void SPI_Slave_Init(SPI_TypeDef *SPI){

    WRITE_REG_FIELD(SPI->CR1,SPI_CR1_BR,3);
    WRITE_REG_FIELD(SPI->CR1,SPI_CR1_CPOL,1);
    WRITE_REG_FIELD(SPI->CR1,SPI_CR1_CPHA,1);

    WRITE_REG_FIELD(SPI->CR1,SPI_CR1_LSBFIRST,0);
    WRITE_REG_FIELD(SPI->CR1,SPI_CR1_SSM,1);
    WRITE_REG_FIELD(SPI->CR1,SPI_CR1_SSI,0);
    WRITE_REG_FIELD(SPI->CR1,SPI_CR1_RXONLY,0);
    WRITE_REG_FIELD(SPI->CR1,SPI_CR1_DFF,0);

    WRITE_REG_FIELD(SPI->CR1,SPI_CR1_MSTR,0);

    WRITE_REG_FIELD(SPI->CR1,SPI_CR2_FRF,0);

}

void SPI_Slave_IRQ(SPI_TypeDef *SPI,uint8_t val){
    WRITE_REG_FIELD(SPI->CR2,SPI_CR2_RXNEIE,val);
}

void SPI_Enable(SPI_TypeDef *SPI,char enable){
    WRITE_REG_FIELD(SPI->CR1,SPI_CR1_SPE,enable);
}


char SPI_Master_Tranfer(SPI_TypeDef *SPI, uint8_t  *data, uint32_t size){
    uint32_t i=0;
    while(i<size){
        while (!(SPI->SR&SPI_SR_TXE));
        SPI->DR = data[i];
        while (!(SPI->SR&SPI_SR_RXNE));
        data[i] = (SPI->DR);
        i++;
    }
    while (!READ_REG_FIELD(SPI->SR,SPI_SR_TXE));
    while (READ_REG_FIELD(SPI->SR,SPI_SR_BSY));

    return(0);

}

void SPI_Slave_Transmit(SPI_TypeDef* SPI,uint8_t txdata){
    SPI->DR = txdata;
}

uint8_t SPI_Slave_Receive(SPI_TypeDef* SPI){
    while (!SPI3->SR&SPI_SR_RXNE);
    return(SPI->DR);
}
