#include "adc.h"

void ADC_GPIO_Config(void){
    WRITE_REG_FIELD(RCC->AHB1ENR,RCC_AHB1ENR_GPIOAEN,1);
    WRITE_REG_FIELD(GPIOA->MODER,GPIO_MODER_MODE1,3);
    WRITE_REG_FIELD(GPIOA->MODER,GPIO_MODER_MODE4,3);
}

void ADC_Init(void){
    
    WRITE_REG_FIELD(RCC->APB2ENR,RCC_APB2ENR_ADC1EN,1);

    WRITE_REG_FIELD(ADC->CCR,ADC_CCR_ADCPRE,1);

    WRITE_REG_FIELD(ADC1->CR1,ADC_CR1_SCAN,1);
    WRITE_REG_FIELD(ADC1->CR1,ADC_CR1_RES,0);

    WRITE_REG_FIELD(ADC1->CR2,ADC_CR2_ALIGN,0);
    WRITE_REG_FIELD(ADC1->CR2,ADC_CR2_EOCS,1);
    WRITE_REG_FIELD(ADC1->CR2,ADC_CR2_CONT,1);

    WRITE_REG_FIELD(ADC1->SMPR2,ADC_SMPR2_SMP1,0);
    WRITE_REG_FIELD(ADC1->SMPR2,ADC_SMPR2_SMP4,0);

    WRITE_REG_FIELD(ADC1->SQR1,ADC_SQR1_L,1);

}

void ADC_enable(uint8_t val){
     WRITE_REG_FIELD(ADC1->CR2,ADC_CR2_ADON,val);
}

void ADC_Start(uint8_t val){
    WRITE_REG_FIELD(ADC1->SQR3,ADC_SQR3_SQ1,val);
    ADC1->SR = 0;
    WRITE_REG_FIELD(ADC1->CR2,ADC_CR2_SWSTART,1);
}


void ADC_WaitForConv(void){
    while(!(READ_BIT(ADC1->SR,ADC_SR_EOC)));
}

uint16_t ADC_GetVal(void){
    return(ADC1->DR);
}